//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.15 at 12:09:25 AM CEST 
//


package com.bank.wsdl;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="messageId" type="{http://com/xsdSchemas/types}str50num"/&gt;
 *         &lt;element name="originatorBankSwiftCode" type="{http://com/xsdSchemas/types}swift"/&gt;
 *         &lt;element name="originatorBankTransactionAccount" type="{http://com/xsdSchemas/types}accountNumber"/&gt;
 *         &lt;element name="recieverBankSwiftCode" type="{http://com/xsdSchemas/types}swift"/&gt;
 *         &lt;element name="recieverBankTransactionAccount" type="{http://com/xsdSchemas/types}accountNumber"/&gt;
 *         &lt;element name="amount" type="{http://com/xsdSchemas/types}dec15_2"/&gt;
 *         &lt;element name="currency" type="{http://com/xsdSchemas/types}str3currency"/&gt;
 *         &lt;element name="currencyDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="statementItems" type="{http://com/xsdSchemas/clearingAndSettlementItem}clearingAndSettlementItem" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageId",
    "originatorBankSwiftCode",
    "originatorBankTransactionAccount",
    "recieverBankSwiftCode",
    "recieverBankTransactionAccount",
    "amount",
    "currency",
    "currencyDate",
    "date",
    "statementItems"
})
@XmlRootElement(name = "mt102Request", namespace = "http://com/xsdSchemas/clearingAndSettlement")
public class Mt102Request {

    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String messageId;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String originatorBankSwiftCode;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String originatorBankTransactionAccount;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String recieverBankSwiftCode;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String recieverBankTransactionAccount;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected BigDecimal amount;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected String currency;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar currencyDate;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(namespace = "http://com/xsdSchemas/clearingAndSettlement", required = true)
    protected List<ClearingAndSettlementItem> statementItems;

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the originatorBankSwiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorBankSwiftCode() {
        return originatorBankSwiftCode;
    }

    /**
     * Sets the value of the originatorBankSwiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorBankSwiftCode(String value) {
        this.originatorBankSwiftCode = value;
    }

    /**
     * Gets the value of the originatorBankTransactionAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorBankTransactionAccount() {
        return originatorBankTransactionAccount;
    }

    /**
     * Sets the value of the originatorBankTransactionAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorBankTransactionAccount(String value) {
        this.originatorBankTransactionAccount = value;
    }

    /**
     * Gets the value of the recieverBankSwiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecieverBankSwiftCode() {
        return recieverBankSwiftCode;
    }

    /**
     * Sets the value of the recieverBankSwiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecieverBankSwiftCode(String value) {
        this.recieverBankSwiftCode = value;
    }

    /**
     * Gets the value of the recieverBankTransactionAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecieverBankTransactionAccount() {
        return recieverBankTransactionAccount;
    }

    /**
     * Sets the value of the recieverBankTransactionAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecieverBankTransactionAccount(String value) {
        this.recieverBankTransactionAccount = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the currencyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrencyDate() {
        return currencyDate;
    }

    /**
     * Sets the value of the currencyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrencyDate(XMLGregorianCalendar value) {
        this.currencyDate = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the statementItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClearingAndSettlementItem }
     * 
     * 
     */
    public List<ClearingAndSettlementItem> getStatementItems() {
        if (statementItems == null) {
            statementItems = new ArrayList<ClearingAndSettlementItem>();
        }
        return this.statementItems;
    }

}
