//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.15 at 12:09:25 AM CEST 
//


package com.bank.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bank.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bank.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mt103Request }
     * 
     */
    public Mt103Request createMt103Request() {
        return new Mt103Request();
    }

    /**
     * Create an instance of {@link Mt900Response }
     * 
     */
    public Mt900Response createMt900Response() {
        return new Mt900Response();
    }

    /**
     * Create an instance of {@link Mt102Request }
     * 
     */
    public Mt102Request createMt102Request() {
        return new Mt102Request();
    }

    /**
     * Create an instance of {@link ClearingAndSettlementItem }
     * 
     */
    public ClearingAndSettlementItem createClearingAndSettlementItem() {
        return new ClearingAndSettlementItem();
    }

}
