//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 10:31:52 PM CEST 
//


package com.xsdschemas.invoice;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.xsdschemas.invoiceitem.InvoiceItem;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageId" type="{http://com/xsdSchemas/types}str50num"/>
 *         &lt;element name="supplierName" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="supplierAddress" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="supplierPib" type="{http://com/xsdSchemas/types}str11pib"/>
 *         &lt;element name="purchaserName" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="purchaserAdress" type="{http://com/xsdSchemas/types}str255"/>
 *         &lt;element name="purchaserPib" type="{http://com/xsdSchemas/types}str11pib"/>
 *         &lt;element name="billingNumber" type="{http://com/xsdSchemas/types}num6"/>
 *         &lt;element name="billingDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="merchandiseValue" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="servicesValue" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="totalServiceAndMerchandiseValue" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="totalDiscount" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="totalTaxes" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="currency" type="{http://com/xsdSchemas/types}str3currency"/>
 *         &lt;element name="amountForPayment" type="{http://com/xsdSchemas/types}dec15_2"/>
 *         &lt;element name="accountNumber" type="{http://com/xsdSchemas/types}accountNumber"/>
 *         &lt;element name="currencyDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="invoiceItems" type="{http://com/xsdSchemas/invoiceItem}invoiceItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageId",
    "supplierName",
    "supplierAddress",
    "supplierPib",
    "purchaserName",
    "purchaserAdress",
    "purchaserPib",
    "billingNumber",
    "billingDate",
    "merchandiseValue",
    "servicesValue",
    "totalServiceAndMerchandiseValue",
    "totalDiscount",
    "totalTaxes",
    "currency",
    "amountForPayment",
    "accountNumber",
    "currencyDate",
    "invoiceItems"
})
@XmlRootElement(name = "invoiceRequest")
public class InvoiceRequest {

    @XmlElement(required = true)
    protected String messageId;
    @XmlElement(required = true)
    protected String supplierName;
    @XmlElement(required = true)
    protected String supplierAddress;
    @XmlElement(required = true)
    protected String supplierPib;
    @XmlElement(required = true)
    protected String purchaserName;
    @XmlElement(required = true)
    protected String purchaserAdress;
    @XmlElement(required = true)
    protected String purchaserPib;
    @XmlElement(required = true)
    protected BigInteger billingNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar billingDate;
    @XmlElement(required = true)
    protected BigDecimal merchandiseValue;
    @XmlElement(required = true)
    protected BigDecimal servicesValue;
    @XmlElement(required = true)
    protected BigDecimal totalServiceAndMerchandiseValue;
    @XmlElement(required = true)
    protected BigDecimal totalDiscount;
    @XmlElement(required = true)
    protected BigDecimal totalTaxes;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected BigDecimal amountForPayment;
    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar currencyDate;
    @XmlElement(required = true)
    protected List<InvoiceItem> invoiceItems;

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * Sets the value of the supplierAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierAddress(String value) {
        this.supplierAddress = value;
    }

    /**
     * Gets the value of the supplierPib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierPib() {
        return supplierPib;
    }

    /**
     * Sets the value of the supplierPib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierPib(String value) {
        this.supplierPib = value;
    }

    /**
     * Gets the value of the purchaserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaserName() {
        return purchaserName;
    }

    /**
     * Sets the value of the purchaserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaserName(String value) {
        this.purchaserName = value;
    }

    /**
     * Gets the value of the purchaserAdress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaserAdress() {
        return purchaserAdress;
    }

    /**
     * Sets the value of the purchaserAdress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaserAdress(String value) {
        this.purchaserAdress = value;
    }

    /**
     * Gets the value of the purchaserPib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaserPib() {
        return purchaserPib;
    }

    /**
     * Sets the value of the purchaserPib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaserPib(String value) {
        this.purchaserPib = value;
    }

    /**
     * Gets the value of the billingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBillingNumber() {
        return billingNumber;
    }

    /**
     * Sets the value of the billingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBillingNumber(BigInteger value) {
        this.billingNumber = value;
    }

    /**
     * Gets the value of the billingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBillingDate() {
        return billingDate;
    }

    /**
     * Sets the value of the billingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBillingDate(XMLGregorianCalendar value) {
        this.billingDate = value;
    }

    /**
     * Gets the value of the merchandiseValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMerchandiseValue() {
        return merchandiseValue;
    }

    /**
     * Sets the value of the merchandiseValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMerchandiseValue(BigDecimal value) {
        this.merchandiseValue = value;
    }

    /**
     * Gets the value of the servicesValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServicesValue() {
        return servicesValue;
    }

    /**
     * Sets the value of the servicesValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServicesValue(BigDecimal value) {
        this.servicesValue = value;
    }

    /**
     * Gets the value of the totalServiceAndMerchandiseValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalServiceAndMerchandiseValue() {
        return totalServiceAndMerchandiseValue;
    }

    /**
     * Sets the value of the totalServiceAndMerchandiseValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalServiceAndMerchandiseValue(BigDecimal value) {
        this.totalServiceAndMerchandiseValue = value;
    }

    /**
     * Gets the value of the totalDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    /**
     * Sets the value of the totalDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDiscount(BigDecimal value) {
        this.totalDiscount = value;
    }

    /**
     * Gets the value of the totalTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTaxes() {
        return totalTaxes;
    }

    /**
     * Sets the value of the totalTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTaxes(BigDecimal value) {
        this.totalTaxes = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the amountForPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountForPayment() {
        return amountForPayment;
    }

    /**
     * Sets the value of the amountForPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountForPayment(BigDecimal value) {
        this.amountForPayment = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the currencyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrencyDate() {
        return currencyDate;
    }

    /**
     * Sets the value of the currencyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrencyDate(XMLGregorianCalendar value) {
        this.currencyDate = value;
    }

    /**
     * Gets the value of the invoiceItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvoiceItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoiceItem }
     * 
     * 
     */
    public List<InvoiceItem> getInvoiceItems() {
        if (invoiceItems == null) {
            invoiceItems = new ArrayList<InvoiceItem>();
        }
        return this.invoiceItems;
    }

}
